# 워크플로우 이름 지정
name: 왜 안돼

# Event: 어떤 이벤트가 발생했을 때 아래 job 로직을 실행시킬 것인지 지정
# push: 코드가 푸시되었을 때
# branches: 어떤 브랜치에 푸시되었을 때
on:
  push:
    branches:
      - main

# Job: 실제로 실행할 하나 이상의 작업을 정의
# Job이 여러 개면 기본적으로 병렬적으로 실행된다.
# My-Deploy-Job: Job 이름을 지정
# runs-on: Job이 실행될 환경을 지정
jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    # steps: Job이 실행될 때 실행할 단계를 정의
    # 하나의 Job은 여러 개의 step으로 구성될 수 있다.
    steps:
      - name: 왜 안 돼 출력하기 # step 이름을 지정
        run: echo "왜 안 돼" # 실행할 명령어를 지정 (리눅스 명령어)

      - name: 명령어 여러 줄 입력하기
        run: | # |를 사용하면 여러 줄의 명령어를 입력할 수 있다.
          echo "첫 번째 줄"
          echo "두 번째 줄"
          echo "세 번째 줄"

      - name: 환경변수 사용하기
        # GITHUB_SHA: GitHub에서 제공하는 환경변수로 현재 커밋의 해시(ID) 값을 가지고 있다.
        # GITHUB_REPOSITORY: GitHub에서 제공하는 환경변수로 현재 레포지토리의 이름을 가지고 있다.
        run: |
          echo "GitHub Action 내장 환경변수 사용하기"
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY

      - name: 커스텀 환경변수 지정해서 출력하고 시크릿키 등록해서 조회하기
        # env: 환경변수를 지정할 수 있다.
        # 환경변수는 $로 접근할 수 있다.
        env:
          MY_AGE: "26"
        run: |
          echo "커스텀 환경변수 사용하기"
          echo $MY_AGE
          echo ${{ secrets.MY_NAME }}
